News/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('news_app.urls'))
]

news_app/urls.py
from django.urls import path
from . import views

app_name='news_app'
urlpatterns = [
    path('', views.home, name='home'),
    path('<str:content_about>/', views.get_all_news_by_content, name='all-by-content-news'), 
    path('<str:category>/<str:content_about>/', views.get_news_by_content, name='get-news'), 
]

news_app/models.py
from django.db import models

# Create your models here.

news_app/views.py
from django.shortcuts import render
from .news_api import get_all_content, get_headlines


# Home - Breaking news
def home(request):
    content_about = 'Breaking news'
    context = {
            'title': content_about,
            'all_articles' : get_headlines()
    }
    template_name = 'news_app/index.html'
    return render(request, template_name, context)


# get news by content_about
def get_all_news_by_content(request, content_about ): 
    context = {
            'title': content_about,
            'all_articles' : get_all_content(content_about)
    }
        
    template_name = 'news_app/index.html'
    return render(request, template_name, context)


# get news by content_about
def get_news_by_content(request, category, content_about):
    context = {
            'title': content_about,
            'all_articles' : get_all_content(content_about)
    }
        
    template_name = 'news_app/index.html'
    return render(request, template_name, context)

news_app/templates/news_app/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">


    <!-- Custom CSS-->
    <link rel="stylesheet" href="{% static 'news_app/css/style.css' %}">

    {% if title %}
    <title>{{title|capfirst}}</title>
    {% else %}
    <title>Hopson Gausi</title>
    {% endif %}
</head>

<body>
    <nav class="navbar navbar-expand-md bg-primary">
        <div class="container">
            <!-- Brand -->
            <a class="navbar-brand" href="{% url 'news_app:home' %}">NEWS</a>

            <!-- Toggler/collapsibe Button -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>

            <!-- Navbar links -->
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'news_app:home' %}">home</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'news_app:all-by-content-news' 'science' %}">science</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'news_app:all-by-content-news' 'business' %}">Business</a>
                    </li>
                    
                    <!-- Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#" id="navbardrop" data-toggle="dropdown">
      Health
    </a>
                        <div class="dropdown-menu bg-primary">
                            <a class="dropdown-item" href="{% url 'news_app:all-by-content-news' 'health' %}">All</a>
                            <a class="dropdown-item" href="{% url 'news_app:get-news' 'health' 'coronavirus' %}">Corona virus</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#" id="navbardrop" data-toggle="dropdown">
      Technology
    </a>
                        <div class="dropdown-menu bg-primary">
                            <a class="dropdown-item" href="{% url 'news_app:all-by-content-news' 'technology' %}">All</a>
                            <a class="dropdown-item" href="{% url 'news_app:get-news' 'technology' 'startups' %}">startups</a>
                            <a class="dropdown-item" href="{% url 'news_app:get-news' 'technology' 'devops' %}">DevOps</a>
                            <a class="dropdown-item" href="{% url 'news_app:get-news' 'technology' 'bitcoin' %}">bitcoin</a>
                            <a class="dropdown-item" href="{% url 'news_app:get-news' 'technology' 'artificial intelligence' %}">AI</a>
                        </div>
                    </li>
                    <!-- Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#" id="navbardrop" data-toggle="dropdown">
      Sports
    </a>
                        <div class="dropdown-menu bg-primary">
                            <a class="dropdown-item" href="{% url 'news_app:get-news' 'sports' 'football' %}">Football</a>
                            <a class="dropdown-item" href="{% url 'news_app:get-news' 'sports' 'nba' %}">NBA</a>
                            <a class="dropdown-item" href="{% url 'news_app:get-news' 'sports' 'netball' %}">netball</a>
                        </div>
                    </li>
                    <!-- Dropdown -->
                    <li class="nav-item dropdown">
                        <a class="nav-link" href="#" id="navbardrop" data-toggle="dropdown">
      Entertainment
    </a>
                        <div class="dropdown-menu bg-primary">
                            <a class="dropdown-item" href="{% url 'news_app:get-news' 'entertainment' 'hollyWood' %}">HollyWood</a>
                            <a class="dropdown-item" href="{% url 'news_app:get-news' 'entertainment' 'music' %}">music</a>
                            <a class="dropdown-item" href="{% url 'news_app:get-news' 'entertainment' 'movies' %}">movies</a>
                        </div>
                    </li>
                    

                  
                </ul>
            </div>
        </div>
    </nav>

{% block content %}
{% endblock content %}

        <footer>
        <p class="text-sm-center">Copyright &copy;2020,Hopson Gausi.</p>
    </footer>
 

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

</html>

news_app/templates/news_app/index.html
{% extends 'news_app/base.html' %}
{% load tz %}
{% load static %}

{% block content %}
    <section id="news-items-list" class="mt-5">
        <div class="container">
            <div class="row">
            {% for article in all_articles %}
                <div class="col-md-4 mb-2">
                    <div class="card" style="width:400px">
                        <img class="card-img-top img-fluid" src="{{ article.urlToImage }}" alt="{{ article.title }}">
                        <div class="post-source mt-2 ml-2 mb-0">
                            <p>Source: {{ article.source.name }} </p>
                           
                             <p>Date: {{ article.publishedAt}}</p>
                           
                        </div>
                        <div class="text-left mt-0 ml-2">
                            <a href="{{ article.url }}" target="_blank">
                                <h4 class="post-title">{{ article.title }}</h4>
                            </a>
                        </div>
                        <div class="post-description ml-2">
                        <p>{{article.description|truncatewords:20}}</p>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
        </div>
    </section>


{% endblock content %}